# config.toml 示例
title = "WJCH"
base_url = "https://wjch611.github.io"

compile_sass = true
ignored_content = ["README.md"]
build_search_index = true
default_language = "en"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
katex_enable = true

[[taxonomies]]
name = "tags"
slug = "tags"

[[taxonomies]]
name = "categories"
slug = "categories"

[extra.social]
github = "wjch611"
twitter = "wjch611"

[extra.show]
links = true
tags = true

[languages.en]
generate_feeds = true
description = "虽千万人，吾往矣！"

[languages.en.translations]
about = "About"
home = "Home"
tags = "Tags"
music = "Music"
links = "Links"
flags = "Flags"
wish = "Wish"
fate = "Fate"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"
